---
title: "CFP"
author: "Kara Godsey"
date: "`r Sys.Date()`"
output:
  rmdformats::downcute
runtime: shiny
---

# College Football Playoff Analysis {.tabset .tabset-fade}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
suppressWarnings(library(DT))
suppressWarnings(library(knitr))
suppressWarnings(library(rmdformats))
suppressWarnings(library(kableExtra))
suppressWarnings(library(ggplot2))
suppressWarnings(library(ggrepel))
suppressWarnings(library(xml2))
suppressWarnings(library(shiny))
suppressWarnings(library(shinythemes))
```

```{r pull_sched}
suppressWarnings(library(rvest))

teams <- c("Florida", "Ohio State", "Alabama","Notre Dame","Clemson","Texas A&M","Iowa State","Cincinnati","Georgia","Miami(FL)","Oklahoma","Indiana","Coastal Carolina","Northwestern","USC","Iowa","North Carolina","BYU","Louisiana","Texas","Colorado","Oklahoma State","NC State","Tulsa","Missouri")
names(teams) <- c("florida","ohio-state","alabama","notre-dame","clemson","texas-am","iowa-state","cincinnati","georgia","miami-fl","oklahoma","indiana","coastal-carolina","northwestern","southern-california","iowa","north-carolina","brigham-young","louisiana-lafayette","texas","colorado","oklahoma-state","north-carolina-state","tulsa","missouri")
urls <- paste0("https://www.sports-reference.com/cfb/schools/",names(teams),"/2020-schedule.html")

get_schedules <- function(url){
  sch <- url %>% read_html() %>% html_nodes("#schedule") %>% .[[1]] %>% html_table
}
```

```{r lapply}
schedules <- lapply(urls,get_schedules)
names(schedules) <- teams
```

```{r write}
writeit <- function(x) {
 write.csv(schedules[[x]], file = paste0("Data/Schedules/",x,".csv")) 
}
```

```{r lapply2}
invisible(lapply(teams, writeit))
```

```{r datafile}
save(schedules, file = "Data/schedules_by_team.Rdata")
```

```{r load}
load("Data/schedules_by_team.Rdata")
```

```{r shiny}
#shiny app to make dropdown to choose schedule

shinyApp(
  ui = fluidPage(titlePanel("2020 Schedules"),
        selectInput("chosenteam", label = strong("Select a team:"), choices = c("Florida", "Ohio State", "Alabama","Notre Dame","Clemson","Texas A&M","Iowa State","Cincinnati","Georgia","Miami(FL)","Oklahoma","Indiana","Coastal Carolina","Northwestern","USC","Iowa","North Carolina","BYU","Louisiana","Texas","Colorado","Oklahoma State","NC State","Tulsa","Missouri")),
        DTOutput('tbl')
        ),
  server = function(input,output) {
    output$tbl = renderDT(
      schedules[[input$chosenteam]], options = list(lengthChange = FALSE)
    )
  }
)

```
